version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test-with-orb:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      
      # 핵심 포인트: 위 3단계(복원->설치->저장)가 이 코드로 완벽히 대체됩니다.
      - node/install-packages:
          pkg-manager: npm
          
      # 테스트 실행
      - run:
          name: Run Tests
          command: npm run test

workflows:
  build-and-test:
    jobs:
      - build-and-test-with-orb